import argparse
import os
import pickle
from typing import Any, Dict, List

import numpy as np
from PIL import Image
from tqdm import tqdm

def save_image(array: np.ndarray, path: str) -> None:
    """Saves a single image array preserving the expected [0, 1] scale."""
    img_float = np.nan_to_num(array.astype(np.float32), nan=0.0, posinf=1.0, neginf=0.0)
    img_float = 255 * np.clip(img_float, 0.0, 1.0)

    # Convert to 8-bit unsigned integer
    img_uint8 = img_float.astype(np.uint8)

    # Handle single-channel (grayscale) vs multi-channel (RGB)
    if img_uint8.ndim == 3 and img_uint8.shape[0] == 1: # Grayscale (C, H, W)
        img_uint8 = img_uint8.squeeze(0)
        pil_img = Image.fromarray(img_uint8, 'L')
    elif img_uint8.ndim == 3 and img_uint8.shape[0] == 3: # RGB (C, H, W)
        img_uint8 = np.transpose(img_uint8, (1, 2, 0)) # Convert to (H, W, C)
        pil_img = Image.fromarray(img_uint8, 'RGB')
    elif img_uint8.ndim == 2: # Grayscale (H, W)
        pil_img = Image.fromarray(img_uint8, 'L')
    else:
        raise ValueError(f"Unsupported image shape: {array.shape}")

    pil_img.save(path)

def main():
    parser = argparse.ArgumentParser(
        description="Visualize images from a .pkl file generated by inferer.py."
    )
    parser.add_argument(
        "pickle_path",
        type=str,
        help="Path to the input .pkl file containing generated samples.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Directory to save the visualized images. Defaults to a folder named after the .pkl file.",
    )
    parser.add_argument(
        "--num_images",
        type=int,
        default=None,
        help="Number of images to save. If not specified, all images will be saved.",
    )
    parser.add_argument(
        "--split_key",
        type=str,
        default=None,
        help="The key for the data split to visualize (e.g., 'train', 'valid'). Defaults to the first key found.",
    )

    args = parser.parse_args()

    # Determine output directory
    output_dir = args.output_dir
    if output_dir is None:
        base_name = os.path.splitext(os.path.basename(args.pickle_path))[0]
        output_dir = f"visualization_{base_name}"

    os.makedirs(output_dir, exist_ok=True)
    print(f"Saving images to: {output_dir}")

    # Load the pickle file
    print(f"Loading data from: {args.pickle_path}")
    with open(args.pickle_path, "rb") as f:
        data: Dict[str, List[Dict[str, Any]]] = pickle.load(f)

    # Determine which split to use
    if args.split_key:
        if args.split_key not in data:
            raise ValueError(f"Split key '{args.split_key}' not found in the pickle file. Available keys: {list(data.keys())}")
        split_key = args.split_key
    else:
        split_key = next(iter(data))
        print(f"No split key provided, using the first one found: '{split_key}'")

    samples = data[split_key]
    num_to_save = args.num_images if args.num_images is not None else len(samples)

    print(f"Found {len(samples)} samples in split '{split_key}'. Saving {num_to_save} images.")

    # Save images
    for i in tqdm(range(min(num_to_save, len(samples))), desc="Saving Images"):
        sample = samples[i]
        image_array = sample["image"]
        
        # Construct filename
        sample_name = sample.get("name", f"sample_{i}")
        class_name = sample.get("class")
        filename = f"{sample_name}"
        if class_name:
            filename += f"_class-{class_name}"
        filename += ".png"
        
        output_path = os.path.join(output_dir, filename)
        
        save_image(image_array, output_path)

    print(f"\nSuccessfully saved {min(num_to_save, len(samples))} images to {output_dir}")

if __name__ == "__main__":
    main()
